### PR TITLE
Update a link in README to live migration documentation

### PR DESCRIPTION
**Pull request by agadelshin**
QEMU changed their link to live migration documentation, this PR fixes broken link in README

### CODE REVIEW

**Review by stradig — APPROVED** [review]
Thank you!

**Comment by agadelshin** [comment]
@stradig you're welcome! CI fails on docker auth probably because PR is from a fork.

**Comment by stradig** [comment]
Right. We will add a workflow to make it easier to merge these kinds of PRs. This will not happen before next week, though.

**Comment by bayandin** [comment]
Thanks again @agadelshin!

Sorry it took so long to merge the PR, we finally added automation for merging PRs from external contributors, and it works 😄

**Pull request merged**
