### PR TITLE
plugin: Remove ComputeUnit from config and PluginResponse

### PR DESCRIPTION
**Pull request by sharnoff**
... and every where else that it filters into.

This is part of the process of moving the ComputeUnit source of truth from the scheduler to the autoscaler-agent (#706). We've already redefined the autoscaler-agent's own config as its source of truth, so this is mostly just following through on the previous deprecation.

### CODE REVIEW

**Comment by sharnoff** [comment]
After thinking some more, I think probably #653 should be merged + deployed before we merge this, alongside sending the compute unit from the autoscaler-agent. Otherwise we'd probably end up delaying deploy of #653.

**Review by shayanh — APPROVED** [review]
lgtm!

**Comment by sharnoff** [comment]
@omrigan LMK if you plan to review; otherwise will merge in ~36h. This isn't urgent, so if you'd like, I'm happy to leave it waiting while you tackle other stuff.

**Review by Omrigan — APPROVED** [review]

**Review by Omrigan — APPROVED** [review]

**Comment by Omrigan** [comment]
> @Omrigan LMK if you plan to review; otherwise will merge in ~36h. This isn't urgent, so if you'd like, I'm happy to leave it waiting while you tackle other stuff.

LGTM. A good net negative line count diff is always welcome :+1:

**Pull request merged**
