### PR TITLE
neonvm-runner-image-loader: Faster rollout

### PR DESCRIPTION
**Pull request by sharnoff**
Specifically, this PR sets `maxUnavailable = 3`, which allows updating up to 3 copies in parallel.

An issue we see during rollout is that it often takes 30+ seconds to create a new neonvm-runner-image-loader on a node, and doing this for many nodes takes an unreasonable amount of time. This improves that.

### CODE REVIEW

**Comment by cicdteam** [comment]
@sharnoff 

why it hardcoded to 3 ? `maxUnavalable` and `maxSurge` could be percentage, like

```
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
```

if we have 10 pods then on rollout 10 old pods will be stopped and 10 new pods will be stared at the moment.

**Comment by sharnoff** [comment]
> why it hardcoded to 3 ?

Yeah, I considered making it a percentage, but I'm not sure if doing a simultaneous image pull cluster-wide could potentially cause issues, so better to be safe.

If you think it's definitely ok, I'll bump it higher, if +1 from @Omrigan.

**Comment by Omrigan** [comment]
> > why it hardcoded to 3 ?
> 
> Yeah, I considered making it a percentage, but I'm not sure if doing a simultaneous image pull cluster-wide could potentially cause issues, so better to be safe.
> 
> If you think it's definitely ok, I'll bump it higher, if +1 from @Omrigan.

I don't see the reason why 100% could failt

**Comment by sharnoff** [comment]
Fair enough, went with 100%

**Comment by sharnoff** [comment]
After trying it out, 100% was definitely the right move :)

**Pull request merged**
