### PR TITLE
Kubernetes 1.24

### PR DESCRIPTION
**Pull request by bayandin**
Resolves https://github.com/neondatabase/autoscaling/issues/124

I haven't tested https://github.com/neondatabase/autoscaling/issues/55

### CODE REVIEW

**Comment by sharnoff** [comment]
I'd love to get this merged soon. Testing #55 can be done after merging, I think. Other than reviewing, is there anything else this PR needs?

**Comment by cicdteam** [comment]
We need update versions for generators as well (in Makefile, scripts and  GitHub actions)

**Comment by bayandin** [comment]
> We need update versions for generators as well (in Makefile, scripts and GitHub actions)

Are you about `CONTROLLER_TOOLS_VERSION`? I kept it on the 0.9 release because 0.10 has switched to k8s 1.25 (see https://github.com/kubernetes-sigs/controller-tools/releases). 
Should we bump it to 0.10 @cicdteam? (they should be compatible across +/-1 minor version, I think)

> Other than reviewing, is there anything else this PR needs?

Nothing else comes to my mind. You can play with it locally
If tests pass, it generally works 😄

**Comment by cicdteam** [comment]
@bayandin 

Yes, you right, controller-gen was bumped to use k8s 1.24 in version 0.9.0, is current 0.9.2 is Ok

Nothing to change at this part.

**Review by cicdteam — APPROVED** [review]

**Review by sharnoff — APPROVED** [review]
Thought there were maybe some changes required in NeonVM controllers (because of the earlier downgrade 1.25 -> 1.23), but those pieces are strictly 1.25+, so we're good :)

**Pull request merged**
