### PR TITLE
vm-builder: Use docker auth

### LINKED ISSUE #814: Implement docker auth for vm-builder
## Problem description / Motivation

`vm-builder` might fail if we send too many requests to docker hub from our hosts:

```
2024/02/19 15:57:36 Setup docker connection
2024/02/19 [15](https://github.com/neondatabase/neon/actions/runs/7960954540/job/21732689596#step:5:16):57:36 Build docker image for virtual machine (disk size 1G): 369495373322.dkr.ecr.eu-central-1.amazonaws.com/vm-compute-node-v15:7960954540
Step 1/53 : FROM debian:bullseye-slim as libcgroup-builder
bullseye-slim: Pulling from library/debian
2024/02/19 15:57:38 toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
Ref https://github.com/neondatabase/neon/actions/runs/7960954540/job/21732689596

To avoid this, we, usually, use authorised access to docker hub, but it seems docker go SDK doesn't pick up auth from DOCKER_CONFIG directory automatically (https://github.com/moby/moby/issues/39377#issuecomment-503589708), so we need to make it possible to pass docker user/password as additional `vm-builder` parameters. 

- Also, to think if it should support different registries (like ECR) and to check it if it should
- Alternatively, we can add to `vm-builder`  `--docker-user`/`--docker-password` parameters

## Implementation ideas
- Use https://github.com/moby/moby/issues/39377#issuecomment-1119914406
- Use https://docs.docker.com/engine/api/sdk/examples/#pull-an-image-with-authentication
- Please note, that we're going to set these parameters from GitHub Secrets, so we should never print them in logs/error messages

### PR DESCRIPTION
**Pull request by sharnoff**
Rebased #817. Recently hit this issue, want to get it across the line.

Fixes #814.

### CODE REVIEW

**Comment by sharnoff** [comment]
Looks like pull auth isn't currently working. In [`build-test-vm`](https://github.com/neondatabase/autoscaling/actions/runs/9575390669/job/26400187030#step:8:11):

```
2024/06/19 04:53:46 Load docker credentials
2024/06/19 04:53:46 Found docker credentials for https://index.docker.io/v1/
2024/06/19 04:53:46 Setup docker connection
2024/06/19 04:53:46 No docker credentials found for docker.io
2024/06/19 04:53:46 Pull source docker image: postgres:16-bullseye
```

**Comment by sharnoff** [comment]
Fixed the index.docker.io legacy weirdness. After that, I saw [this sequence of logs](https://github.com/neondatabase/autoscaling/actions/runs/9575793460/job/26401201486#step:8:14) previously, and was a little worried:

```
2024/06/19 05:40:26 Pull source docker image: postgres:16-bullseye
2024/06/19 05:40:28 Build docker image for virtual machine (disk size 1G): neondatabase/vm-postgres-16-bullseye:924e783.9575793460
2024/06/19 05:40:28 Error response from daemon: No such image: postgres:16-bullseye
```

But I tested locally after logging in with my dockerhub credentials and it seems totally fine.

Still not 100% convinced that we're successfully logged in for image pulls during the build, but :shrug:

**Review by bayandin — COMMENTED** [review]
> Still not 100% convinced that we're successfully logged in for image pulls during the build, but 🤷

Exactly the point at which I stopped in my PR working on the same 🤣  


Let's try to test it through; we can create private repos (in our dockerhub account), copy some images there and replace public images with their private counterparts. 
Then if auth doesn't work it'll fail

**Comment by bayandin** [comment]
It seems it doesn't work as expected:
```
Run bin/vm-builder -src neondatabase/test-private:alpine-3.16 -dst neondatabase/vm-alpine:3.16
2024/09/10 13:31:01 Load docker credentials
2024/09/10 13:31:01 Found docker credentials for https://index.docker.io/v1/
2024/09/10 13:31:01 Setup docker connection
2024/09/10 13:31:01 Pull source docker image: neondatabase/test-private:alpine-3.1[6](https://github.com/neondatabase/autoscaling/actions/runs/10793525437/job/29935653185#step:8:7)
2024/09/10 13:31:02 Error response from daemon: pull access denied for neondatabase/test-private, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

https://github.com/neondatabase/autoscaling/actions/runs/10793525437/job/29935653185#step:8:9

Tested with https://github.com/neondatabase/autoscaling/pull/977/commits/90ecc6322b3a78ef5e33477de74b06d03098e17e

**Comment by bayandin** [comment]
[It works!](https://github.com/neondatabase/autoscaling/actions/runs/10796891907)

**Review by bayandin — APPROVED** [review]

**Pull request merged**
