### PR TITLE
Use go 1.20

### PR DESCRIPTION
**Pull request by bayandin**
Use latest go 1.20

### CODE REVIEW

**Comment by sharnoff** [comment]
Broadly in favor of doing this. Can we set `-buildvcs=false`? Go 1.20 changed (read: [broke](https://github.com/golang/go/issues/59068)) the handling of git worktrees. (although, git worktrees also wouldn't work inside a container even if they implemented it correctly (because the referenced .gitdir wouldn't be in the container); they just didn't recognize .git _files_ prior to 1.20, so `-buildvcs=auto` didn't see a git repo)

**Comment by tychoish** [comment]
Can we hold off on this until cloud moves to 1.20 (which I think is quasi blocked on the fact that some things make the linter oom with 1.20?) just so that it's almost possible to develop both of them on the same system/etc

**Comment by tychoish** [comment]
> I _think_ that should be fixed by installing the right version of golangci-lint, unless there's a different OOM.

I'm giving this a second chance now, so we'll see. Still think we shouldn't get ahead of cloud but I don't think it matters.

**Comment by bayandin** [comment]
> > I _think_ that should be fixed by installing the right version of golangci-lint, unless there's a different OOM.
> 
> I'm giving this a second chance now, so we'll see. Still think we shouldn't get ahead of cloud but I don't think it matters.

I don't mind waiting until we do it in cloud repo first. Is there a PR for this?

**Comment by tychoish** [comment]
> I don't mind waiting until we do it in cloud repo first. Is there a PR for this?

Just made it!

**Comment by bayandin** [comment]
> Can we set `-buildvcs=false`?

Added `GOFLAGS=-buildvcs=false` to Makefile.
I also passed the variable to all docker build/buildx commands. But can we skip this part or it's required as well?

**Review by tychoish — APPROVED** [review]
is the e2e test failure related? I didn't look, but seems like having a green checkmark would be nice :) 

Also, I think for the cloud docker images we pin to specific point-releases and here we're letting docker/etc (I think?) roll forward on point releases. I'm pretty confident in the stability of Go's release process, but I wanted to make sure we were ok with that difference, and its implications.

**Review by sharnoff — APPROVED** [review]
Sorry for such a late reply. I think we should only track the minor release, but if there's issues with a particular version we can pin to a patch until those are resolved.

**Pull request merged**
