### PR TITLE
neonvm/runner: Print error messages where errors happen.

### PR DESCRIPTION
**Pull request by hlinnaka**
I got a "File not found" error when fiddling around, and it was hard
to tell which command it came from. This should make it easier to
pinpoint failures in the future.

In the passing, standardize existing log.Printf() messages to not
include newline at the end. Printf() adds a newline implicitly if you
omit it.

### CODE REVIEW

**Review by sharnoff — APPROVED** [review]
Looks good, thanks! Newline changes + locality `neonvm/runner` should be reflected in the PR title (and/or split into separate PR(s)).

**Comment by hlinnaka** [comment]
- Moved the typo fix to PR #407 (and added one more typo fix there)
- Separated commits to add new log messages, and to removed the newlines from existing ones.

**Comment by hlinnaka** [comment]
> locality neonvm/runner should be reflected in the PR title 

Added "neonvm/runner:" prefix.

Looking at the commit history, we don't have much consistency on that in the commit messages. So I just updated the PR title but didn't add it to the commit messages.

Matter of taste and style, for sure, but I don't see much point in those prefixes in commit messages in general. You can always use `--stat` to see which files are affected.

**Review by sharnoff — APPROVED** [review]
> Looking at the commit history, we don't have much consistency on that in the commit messages.
>
> [ ... ]
>
> Matter of taste and style, for sure, but I don't see much point in those prefixes in commit messages in general.

Yeah, I get that. I've personally found a lot of utility in having these sorts of things available when trying to quickly associate a change in behavior with possible PRs/commits that could have caused it. `--stat` is sometimes quite long, and IMO less effective than descriptive PR/commit names. So, on the whole, I've found it to be a little bit of up-front effort that saves time when you really need it. They've also been useful while writing release notes, but that's lower priority :sweat_smile:

---

All that aside, this PR's good :) There's other occurrences of `Printf.*?\\n;` in various places, but presumably those are outside the scope of this PR.

**Pull request merged**
