### PR TITLE
neonvm: enable using bpftrace

### PR DESCRIPTION
**Pull request by problame**
Hopefully this is enough to make bpftrace work.

### CODE REVIEW

**Comment by problame** [comment]
Kernel build running in https://github.com/neondatabase/autoscaling/actions/runs/6870889645

**Comment by problame** [comment]
Kernel build running in https://github.com/neondatabase/autoscaling/actions/runs/6870971183

**Comment by problame** [comment]
bpftrace doesn't work yet with this.

**Comment by problame** [comment]
Building and pushing kernel image to https://github.com/neondatabase/autoscaling/actions/runs/6890019738 (new tag, so, won't affect existing builds)

**Comment by problame** [comment]
Fixes after force push, running in https://github.com/neondatabase/autoscaling/actions/runs/6890133315

**Comment by problame** [comment]
https://github.com/neondatabase/autoscaling/actions/runs/6890199472

**Comment by Omrigan** [comment]
Talked to @problame, changes were needed only during hackathon.

**Pull request closed without merging**
