### PR TITLE
Set hostname in the VM to "vm-<compute name>"

### PR DESCRIPTION
**Pull request by hlinnaka**
Mainly, to have it show up in the shell prompt, when you ssh into a compute VM. Which in turn can help to avoid mistakes like mixing up different computes.

### CODE REVIEW

**Comment by sharnoff** [comment]
+1 that this should change, I think I'd rather make this change on the VM spec, although not 100% sure. WDYT?

cc @Omrigan

**Comment by hlinnaka** [comment]
> +1 that this should change, I think I'd rather make this change on the VM spec, although not 100% sure. WDYT?

No opinion, this just seemed like the simplest way to accomplish it.

**Comment by hlinnaka** [comment]
I just noticed that this PR contains a bunch of unrelated changes. Sorry about that! I'll clean it up..

**Comment by hlinnaka** [comment]
> I just noticed that this PR contains a bunch of unrelated changes. Sorry about that! I'll clean it up..

Done.

**Comment by Omrigan** [comment]
> +1 that this should change, I think I'd rather make this change on the VM spec, although not 100% sure. WDYT?
> 
> cc @Omrigan

We currently don't have a way to configure hostname in the spec, so why introduce? I don't see a use-case for having a custom hostname, so I like the approach of this PR.

**Review by Omrigan — APPROVED** [review]

**Pull request merged**
