### PR TITLE
Kubernetes 1.25

### PR DESCRIPTION
**Pull request by bayandin**
This PR includes the following

Version changes:
- Kubernetes 1.25.10 ~1.25.9~ (from 1.24.13)
- Kubernetes API  0.25.10 ~0.25.9~ (from 0.24.13)
- kubectl 1.26.5 ~1.26.4~ (from 1.25.9)
- Controller Tools 0.10.0 (from 0.9.2)
- ❗ Code Generator 0.25.10 ~0.25.9~ (from 0.26.0) -- Downgrade to match k8s API version ❗ 
- kind image kindest/node:v1.25.9 ~v1.25.8~ (from v1.24.12)

Autogenerated changes:
- `make generate`
- `make manifests`

Other changes:
- Uncommented changes in `neonvm/controllers/virtualmachinemigration_controller.go` (related to `controllerutil.RemoveFinalizer`)
- `make generate` passes CONTROLLER_TOOLS_VERSION and CODE_GENERATOR_VERSION via build-arg to avoid defining version in several places
- Applied changes to Cluster Autoscaler proposed in https://github.com/neondatabase/autoscaling/pull/246#issuecomment-1557715505

### CODE REVIEW

**Comment by cicdteam** [comment]
I prefer merge #245 first as there were a lot of changes to the controllers.

**Comment by sharnoff** [comment]
I've confirmed this fixes #55

**Review by cicdteam — APPROVED** [review]

**Review by sharnoff — APPROVED** [review]
Looks good :)

**Comment by sharnoff** [comment]
Heads-up: cluster-autoscaler (#232) has now been merged. The following patch should be sufficient to update:

```diff
diff --git a/cluster-autoscaler/ca.patch b/cluster-autoscaler/ca.patch
index 06cc0c0..9b9b497 100644
--- a/cluster-autoscaler/ca.patch
+++ b/cluster-autoscaler/ca.patch
@@ -1,5 +1,5 @@
 diff --git a/cluster-autoscaler/utils/kubernetes/listers.go b/cluster-autoscaler/utils/kubernetes/listers.go
-index b70ca1db..85f1473f 100644
+index d0033550f..fa3c2ec30 100644
 --- a/cluster-autoscaler/utils/kubernetes/listers.go
 +++ b/cluster-autoscaler/utils/kubernetes/listers.go
 @@ -17,14 +17,19 @@ limitations under the License.
@@ -12,7 +12,7 @@ index b70ca1db..85f1473f 100644
  	appsv1 "k8s.io/api/apps/v1"
  	batchv1 "k8s.io/api/batch/v1"
  	apiv1 "k8s.io/api/core/v1"
- 	policyv1 "k8s.io/api/policy/v1beta1"
+ 	policyv1 "k8s.io/api/policy/v1"
 +	"k8s.io/apimachinery/pkg/api/resource"
 +	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
  	"k8s.io/apimachinery/pkg/fields"
diff --git a/cluster-autoscaler/ca.tag b/cluster-autoscaler/ca.tag
index 601b81b..7ac956d 100644
--- a/cluster-autoscaler/ca.tag
+++ b/cluster-autoscaler/ca.tag
@@ -1 +1 @@
-cluster-autoscaler-1.24.1
+cluster-autoscaler-1.25.1
```

**Comment by sharnoff** [comment]
@bayandin is OOO — want to include this in a release later today, so: merging this without waiting. There haven't been any relevant changes since the last rebase, so should be ok.

**Pull request merged**
